# Generated by Django 3.2.25 on 2024-03-22 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='laugh',
            field=models.ManyToManyField(blank=True, related_name='post_laughs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='love',
            field=models.ManyToManyField(blank=True, related_name='post_loves', to=settings.AUTH_USER_MODEL),
        ),
    ]
