# Generated by Django 3.2.25 on 2024-03-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='../default_profile_j48glb', upload_to='images/'),
        ),
    ]
